# Shell variables
# Generated by 'wal'
wallpaper='/home/zraekl/.config/hypr/wallpapers/pxfuel.jpg'

# Special
background='#1b130d'
foreground='#f1e3ab'
cursor='#f1e3ab'

# Colors
color0='#1b130d'
color1='#A45028'
color2='#A36634'
color3='#A16D47'
color4='#D29239'
color5='#B68B5B'
color6='#DEA255'
color7='#f1e3ab'
color8='#a89e77'
color9='#A45028'
color10='#A36634'
color11='#A16D47'
color12='#D29239'
color13='#B68B5B'
color14='#DEA255'
color15='#f1e3ab'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
