--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/zraekl/.config/hypr/wallpapers/pxfuel.jpg"

-- Special
background="#1b130d"
foreground="#f1e3ab"
cursor="#f1e3ab"

-- Colors
color0="#1b130d"
color1="#A45028"
color2="#A36634"
color3="#A16D47"
color4="#D29239"
color5="#B68B5B"
color6="#DEA255"
color7="#f1e3ab"
color8="#a89e77"
color9="#A45028"
color10="#A36634"
color11="#A16D47"
color12="#D29239"
color13="#B68B5B"
color14="#DEA255"
color15="#f1e3ab"
